//
//  PortfolioWorker.swift
//  Rijksmuseum
//
//  Created by Tim Edwards on 29/07/2018.
//  Copyright (c) 2018 Tim Edwards. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class PortfolioWorker{
    func fetchListings(completion: (Result<[ArtStub], Error>)->Void){
//        let artRequest = ArtRequest(page: 0, starredOnly: false)
//        artService.getArtResults(withRequest: artRequest) {[weak self] (result) in
//            guard let sSelf = self else {return}
//            switch result {
//            case .success(let artObjects):
//                let portfolioListings = artObjects.map({
//                    return PortfolioViewModel.PortfolioListing(imageUrl: $0.imageUrl,
//                                                               associatedObject: $0)
//                })
//                sSelf.interface?.viewModel = PortfolioViewModel(portfolioListings: portfolioListings)
//            case .failure(_):
//                fatalError()
//            }
//        }
    }
}
