//
//  PortfolioWorker.swift
//  Rijksmuseum
//
//  Created by Tim Edwards on 29/07/2018.
//  Copyright (c) 2018 Tim Edwards. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ArtPrimitiveSource {
    func fetchPrimitives(completion: @escaping (Result<[ArtPrimitive], Error>)->Void)
}

class ArtPrimitivesWorker{
    let artPrimitiveSource:ArtPrimitiveSource
    init(artPrimitiveSource:ArtPrimitiveSource) {
        self.artPrimitiveSource = artPrimitiveSource
    }
    func fetchPrimitives(completion: @escaping (Result<[ArtPrimitive], Error>)->Void){
        artPrimitiveSource.fetchPrimitives { (result) in
            switch result {
            case .success(let artPrimitives):
                completion(.success(artPrimitives))
            case .failure(_):
                fatalError()
            }
        }
    }
}
