//
//  PortfolioPresenter.swift
//  Rijksmuseum
//
//  Created by Tim Edwards on 29/07/2018.
//  Copyright (c) 2018 Tim Edwards. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PortfolioPresentationLogic{
    func presentSomething(response: Portfolio.Something.Response)
}

class PortfolioPresenter: PortfolioPresentationLogic{
    weak var viewController: PortfolioDisplayLogic?
    
    // MARK: Do something
    func presentSomething(response: Portfolio.Something.Response){
        let viewModel = Portfolio.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
