//
//  PortfolioModels.swift
//  Rijksmuseum
//
//  Created by Tim Edwards on 29/07/2018.
//  Copyright (c) 2018 Tim Edwards. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Portfolio{
    enum FetchArt{
        struct Request{}
        struct Response{}
        struct ViewModel{
            struct Listing {
                let imageUrl:URL
            }
            var listings:[Listing]
        }
    }

    static func build()->PortfolioViewController{
        let presenter = PortfolioPresenter()
        let router = PortfolioRouter()
        let interactor = PortfolioInteractor(presenter: presenter)
        let viewController = PortfolioViewController(interactor: interactor,
                                                     router: router)
        presenter.viewController = viewController
        router.viewController = viewController
        router.interactorData = interactor
        return viewController
    }
}
