//
//  PortfolioInteractor.swift
//  Rijksmuseum
//
//  Created by Tim Edwards on 29/07/2018.
//  Copyright (c) 2018 Tim Edwards. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PortfolioInteractorInput{
    func doSomething(request: Portfolio.FetchArt.Request)
}

protocol PortfolioDataStore{
    //var name: String { get set }
}

class PortfolioInteractor: PortfolioInteractorInput, PortfolioDataStore{
    var presenter: PortfolioPresenterInput?
    var worker: PortfolioWorker?
    //var name: String = ""
    
    // MARK: Do something
    func doSomething(request: Portfolio.FetchArt.Request){
        worker = PortfolioWorker()
        worker?.fetchListings()
        
        let response = Portfolio.FetchArt.Response()
        presenter?.presentSomething(response: response)
    }
}
