whitelist_rules:
- anyobject_protocol
- array_init
- block_based_kvo
- class_delegate_protocol
- closing_brace
- closure_body_length
- closure_end_indentation
- closure_parameter_position
- closure_spacing
- collection_alignment
- colon
- comma
- compiler_protocol_init
- conditional_returns_on_newline
- contains_over_filter_count
- contains_over_filter_is_empty
- contains_over_first_not_nil
- contains_over_range_nil_comparison
- control_statement
- convenience_type
- custom_rules
- cyclomatic_complexity
- deployment_target
- discarded_notification_center_observer
- discouraged_direct_init
- discouraged_object_literal
- discouraged_optional_boolean
- duplicate_enum_cases
- duplicate_imports
- dynamic_inline
- empty_collection_literal
- empty_count
- empty_enum_arguments
- empty_parameters
- empty_parentheses_with_trailing_closure
- empty_string
- empty_xctest_method
- enum_case_associated_values_count
- expiring_todo
- explicit_init
- explicit_self
- extension_access_modifier
- fallthrough
- fatal_error_message
- file_header
- file_length
- file_name
- file_name_no_space
- first_where
- flatmap_over_map_reduce
- for_where
- force_cast
- force_try
- function_body_length
- function_default_parameter_at_end
- function_parameter_count
- generic_type_name
- identical_operands
- identifier_name
- implicit_getter
- implicit_return
- indentation_width
- inert_defer
- is_disjoint
- joined_default_parameter
- large_tuple
- last_where
- leading_whitespace
- legacy_cggeometry_functions
- legacy_constant
- legacy_constructor
- legacy_hashing
- legacy_multiple
- legacy_nsgeometry_functions
- legacy_random
- let_var_whitespace
- line_length
- literal_expression_end_indentation
- lower_acl_than_parent
- mark
- multiline_arguments
- multiline_arguments_brackets
- multiline_function_chains
- multiline_literal_brackets
- multiline_parameters
- multiline_parameters_brackets
- multiple_closures_with_trailing_closure
- nesting
- no_fallthrough_only
- no_space_in_method_call
- notification_center_detachment
- nslocalizedstring_key
- nsobject_prefer_isequal
- opening_brace
- operator_usage_whitespace
- operator_whitespace
- optional_enum_case_matching
- orphaned_doc_comment
- overridden_super_call
- override_in_extension
- pattern_matching_keywords
- prefer_self_type_over_type_of_self
- private_action
- private_outlet
- private_over_fileprivate
- private_unit_test
- prohibited_interface_builder
- prohibited_super_call
- protocol_property_accessors_order
- quick_discouraged_call
- quick_discouraged_focused_test
- quick_discouraged_pending_test
- raw_value_for_camel_cased_codable_enum
- reduce_boolean
- reduce_into
- redundant_discardable_let
- redundant_nil_coalescing
- redundant_objc_attribute
- redundant_optional_initialization
- redundant_set_access_control
- redundant_string_enum_value
- redundant_type_annotation
- redundant_void_return
- return_arrow_whitespace
- shorthand_operator
- single_test_class
- sorted_first_last
- statement_position
- static_operator
- strict_fileprivate
- strong_iboutlet
- superfluous_disable_command
- switch_case_alignment
- switch_case_on_newline
- syntactic_sugar
- todo
- toggle_bool
- trailing_closure
- trailing_newline
- trailing_semicolon
- type_body_length
- type_contents_order
- type_name
- unavailable_function
- unneeded_break_in_switch
- unneeded_parentheses_in_closure_argument
- unowned_variable_capture
- unused_capture_list
- unused_closure_parameter
- unused_control_flow_label
- unused_declaration
- unused_enumerated
- unused_import
- unused_optional_binding
- unused_setter_value
- valid_ibinspectable
- vertical_parameter_alignment
- vertical_parameter_alignment_on_call
- vertical_whitespace
- vertical_whitespace_closing_braces
- void_return
- weak_delegate
- xct_specific_matcher
- xctfail_message
- yoda_condition
- trailing_whitespace
# - attributes
# - discouraged_optional_collection       # Optional collections semantically make sense
# - explicit_acl                          # Too verbose
# - explicit_enum_raw_value
# - explicit_top_level_acl                # Maybe enable for frameworks in the future
# - explicit_type_interface               # Unnecessary
# - file_types_order
# - force_unwrapping
# - implicitly_unwrapped_optional
# - missing_docs                          # Unnecessary
# - modifier_order
# - nimble_operator                       # Less readable
# - no_extension_access_modifier          # Unnecessary
# - no_grouping_extension
# - nslocalizedstring_require_bundle      # Unnecessary for single project
# - number_separator                      # Unnecessary
# - object_literal                        # Object literals = bad
# - prefixed_toplevel_constant            # Unnecessary
# - required_deinit                       # Unnecessary
# - required_enum_case                    # Unnecessary
# - sorted_imports
# - trailing_comma
# - untyped_error_in_catch                # Unnecessary
# - vertical_whitespace_between_cases
# - vertical_whitespace_opening_braces

excluded:
- Pods # to avoid linting cocoapods
- .bundle # to avoid breaking bundler in the CI
identifier_name:
    excluded: # excluded via string array
    - id
